### ISSUE TITLE
Switch build package management from Yarn to NPM 5

### ISSUE THREAD

**Issue by axefrog** [frptools/collectable#50]
NPM 5 seems pretty solid, and I'd like to see if it fixes the Travis build issue.

**Comment by SimonMeskens** [comment]
I'm having issues getting nodegit to work with Node8 and NPM5. I was about to downgrade my NPM and/or Node to get Collectable to install.

**Comment by axefrog** [comment]
Oh, just remove NodeGit. It was there for the CLI, which I never got around to implementing.

**Comment by axefrog** [comment]
Done. Removed NodeGit as well.
