### ISSUE TITLE
If yarn is preferred, why not commit the yarn.lock file?

### ISSUE THREAD

**Issue by ariesshrimp** [frptools/collectable#57]
In [the CONTRIBUTING doc](https://github.com/frptools/collectable/blob/master/CONTRIBUTING.md#building), it's mentioned that it's best to install and build the packages using `yarn`. But there isn't a [`yarn.lock`](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control) file committed in the codebase. Is there a reason not to? `yarn.lock` is not listed in the [`.gitignore`](https://github.com/frptools/collectable/blob/master/.gitignore) or [`.npmignore`](https://github.com/frptools/collectable/blob/master/.npmignore) files.

**Comment by SimonMeskens** [comment]
The build changed very recently to NPM5

**Comment by ariesshrimp** [comment]
I assume that means you don't want to instruct people that they _should_ be using `yarn` any longer?

**Comment by SimonMeskens** [comment]
I'm not sure, I just came along right before you to help with some code, so I went through the same process and know some of the answers :)

@axefrog Has all the answers, but I think he's having a rather busy week, so we'll be patient for a bit

**Comment by axefrog** [comment]
Hey guys, sorry for my absence. Had the flu, felt like death, etc.

Simon is right. The parts of the CONTRIBUTING doc related to implementation specifics and the build process are outdated. References to commit standards and other conventions still apply though.
