### ISSUE TITLE
setIn() second parameter is treated as a value

### ISSUE THREAD

**Issue by ariesshrimp** [frptools/collectable#61]
In #55 I alluded to this, but currently `setIn()` has this API:

```typescript
setIn([path to your destination in target collection], valueToSet, targetCollection)
```

thus:

```typescript
setIn(['a', 'b', 'c', 'd', 'e'], true, from({}))
// expected: from({a: {b: {c: {d: {e: true}}}}}) 👌🏻
```

However, the README describes the API like so:

```typescript
setIn(['foo', 'bar'], x => 'baz', from({})); 
// expected: <{foo: <{bar: 'baz'}>, xyz: ...> ❌
// actual: <{foo: <{bar: x => 'baz'}>, xyz: ...> 😱
```

Note that in the above example, the expected value of the resulting collection at `bar` is _`'baz'`_. In actuality, the resulting value will be `x => 'baz'`, because `setIn()` will set the target value as _a reference to the function_, rather than evaluating the function to get `'baz'`

To get the results described in the README, the example would read:

```typescript
setIn(['foo', 'bar'], 'baz', from({})); 
// expected: <{foo: <{bar: 'baz'}>, xyz: ...> 👌🏻
```

I think this might just be a typo in the README, but I want to make sure first.

**Comment by ariesshrimp** [comment]
If the issue is just a typo, the attached PR makes the described change.

**Comment by axefrog** [comment]
Yep, I suspect the fact that the example followed the `updateIn` signature had something to do with it...
