### ISSUE TITLE
NPM Failing on @collectable/* references and @frptools/* references

### ISSUE THREAD

**Issue by jk121960** [frptools/collectable#69]
I wanted to check the lib out on NPM and received numerous "Cannot Read Data for" for collectable references and "Invalid Name" errors for frptools. I am interested to check it out, if the maintainer could correct the config files. Thanks

**Comment by axefrog** [comment]
Hey there, I can't reproduce this on my end. Are you still having trouble? It's possible that NPM was experiencing some temporary issues on their side.

**Comment by jk121960** [comment]
Here is the cli, attached is the npm debug thanks

zenlinux Prolecto_oAuthRestTBA # npm install collectable
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
"collectable"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@collectable/map"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!
 /root/ardour-projects/documents-backup/Projects/Prolecto_oAuthRestTBA/npm-debug.log
zenlinux Prolecto_oAuthRestTBA #


Gerald Klein DBA

jk121960@gmail.com

jk@zognet.com

708-599-0352


Arch, Gentoo I3, Ranger & Vim the coding triple threat.

Linux registered user #548580

Brought to you by the Amish Mafia

**Comment by axefrog** [comment]
You're on an extremely outdated version of NPM, which I suspect is why you're having a problem. Current version is 6+ (you're still on 3.x).

Others have had similar problems, and the cause is the same. See: 
https://stackoverflow.com/questions/37038269/npm-err-invalid-name-angular-core-when-following-the-angular-2-quick-start

**Comment by jk121960** [comment]
OK thanks, Oddly didn't have any problem with other packages, I will
upgrade and see, thanks again

Gerald Klein DBA

jk121960@gmail.com

jk@zognet.com

708-599-0352


Arch, Gentoo I3, Ranger & Vim the coding triple threat.

Linux registered user #548580

Brought to you by the Amish Mafia

**Comment by jk121960** [comment]
I finally got around to checking it and you were right I installed latest
and it went in fine. Thanks again

Gerald Klein DBA

jk121960@gmail.com

jk@zognet.com

708-599-0352


Arch, Gentoo I3, Ranger & Vim the coding triple threat.

Linux registered user #548580

Brought to you by the Amish Mafia
